export default {
    UPDATE_SEARCH_INPUTS: 'UPDATE_SEARCH_INPUTS',
    GET_HOTEL_RESULTS_REQUEST: 'GET_HOTEL_RESULTS_REQUEST',
    GET_HOTEL_RESULTS_SUCCESS: 'GET_HOTEL_RESULTS_SUCCESS',
    GET_HOTEL_RESULTS_ERROR: 'GET_HOTEL_RESULTS_ERROR'
};
